### ISSUE TITLE
I could not run the code

### ISSUE THREAD

**Issue by danriz** [quandyfactory/download_tweets#1]
Here the code and error message: I tried python 2.6 and python 2.7 in windows:

C:>C:\Python26\python.exe C:\Python26\download_tweets.py
Enter your username (e.g. RyanMcGreal) below.
Username: securityaffairs
Fetching page 1...
Traceback (most recent call last):
  File "C:\Python26\download_tweets.py", line 72, in <module>
    get_tweets(options.username, options.output_filename)
  File "C:\Python26\download_tweets.py", line 50, in get_tweets
    this_tweetlist = [tweet[key] for key in keys]
TypeError: string indices must be integers

**Comment by quandyfactory** [comment]
Hi riznad,

Unfortunately, the twitter API has changed since the last time I posted
that code. I'm in the process of updating it and will let you know once
it's working again.

Kind Regards,
Ryan

**Comment by danriz** [comment]
Hello Ryan;
Please reply to this email address.
I am waiting.
Thank you for your interest.
Kind Regards.
